
	err, ret = xpcall(function()
	
	    if math.random(40000) > 39996 then
		    --print("Received!! : TID = "..utils.GetThreadId())  
			print("Receive: "..math.floor((server:GetReceiveBytesPerSecond()/1024)).."KB/s,\tPackages: "..server:GetReceiveCountPerSecond().." pkg/sec,\t Current clients: "..server:GetTcpClientCount())
			print("Send:    "..math.floor((server:GetSentBytesPerSecond()/1024)).."KB/s,\tPackages: "..server:GetSentCountPerSecond().." pkg/sec")
		end
		
		--if math.random(30000) > 10000 then
		    local uid = utils.GetClientUid()
			--print(uid)
			server:SendStringToClient(uid, "AAAAAAAAAAAAAAASSSSSSSSSSSSSSSSSSSDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAASSSSSSSSSSSSSSSSSSSDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAASSSSSSSSSSSSSSSSSSSDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAASSSSSSSSSSSSSSSSSSSDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAASSSSSSSSSSSSSSSSSSSDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAASSSSSSSSSSSSSSSSSSSDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAASSSSSSSSSSSSSSSSSSSDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAASSSSSSSSSSSSSSSSSSSDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAASSSSSSSSSSSSSSSSSSSDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAASSSSSSSSSSSSSSSSSSSDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAASSSSSSSSSSSSSSSSSSSDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAASSSSSSSSSSSSSSSSSSSDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAASSSSSSSSSSSSSSSSSSSDDDDDDDDDDDDDDDDDDDD")
			
		--end
		
	end, debug.traceback)
	
	if (ret) then
		--print("complicated(true) --> ", err, ret)
		--server:Log(err)   
		end



